# Generated by Django 4.0.6 on 2022-07-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='generic',
            field=models.TextField(),
        ),
    ]
