# Generated by Django 4.0.6 on 2022-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='elements',
            field=models.TextField(default='-'),
        ),
    ]
