# Generated by Django 4.0.6 on 2022-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='behance',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='store',
            name='dribbble',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter',
            field=models.TextField(default='-'),
        ),
    ]
