# Generated by Django 4.0.6 on 2022-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_behance_store_dribbble_store_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='set_name',
            field=models.TextField(default='-'),
        ),
    ]
