# Generated by Django 4.0.6 on 2022-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='link',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='store',
            name='tell',
            field=models.TextField(default='-'),
        ),
    ]
