# Generated by Django 4.0.6 on 2022-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='behance',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='dribbble',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='link',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='tell',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
